Farama-Foundation/HighwayEnv

highway_env/envs/common/abstract.py, highway_env/envs/common/graphics.py, highway_env/road/graphics.py, highway_env/vehicle/graphics.py
In this PR, I propose an additional feature allowing offscreen rendering. This might be useful when computations are performed on servers or cloud platforms. On offscreen mode, the automatic_rendering is also disabled to speed up the simulations.
=> implementing an offscreen rendering mode

demo_stack.ipynb, docs/demo_stack.ipynb, highway_env/envs/common/abstract.py, highway_env/envs/common/graphics.py, highway_env/envs/common/observation.py, highway_env/road/graphics.py, highway_env/vehicle/graphics.py
Here I added to the observation class a DQN-like stack of frames rendered by the EnvViewer class. This feature has only be used in the offscreen mode proposed in a recent PR. 
There is a short notebook demo_stack.ipynb at the doc folder of the project to briefly show how it behaves.
=> Grayscale obs

highway_env/envs/__init__.py, highway_env/envs/summon_env.py, highway_env/vehicle/behavior.py
Suggesting a new environment, similar to "parking-v0", with the following changes:
- Vehicle starts in a particular parking spot
- Parking lot is populated with random vehicles (either in the "middle lane" or in other parking spots)
- Goal is in the "middle lane", either to the left or right side of the parking lot.
This gym environment could be a useful way to train "Summon" type behavior (a la Tesla).
I think it should be ready, but please review to see what changes you may need to add this to the repository.
=> Make summon environment

README.md
Update Usage in README to include the import of gym library
=> Add missing import for gym library

highway_env/envs/common/graphics.py, highway_env/envs/merge_env.py, highway_env/envs/parking_env.py, highway_env/envs/summon_env.py, highway_env/road/graphics.py, highway_env/road/road.py, highway_env/vehicle/dynamics.py, highway_env/vehicle/graphics.py, highway_env/vehicle/kinematics.py
For some applications(like what I have in mind), it may be useful to separate vehicle to vehicle collision and vehicle to obstacle collision.
Please let me know if you think there is something wrong with these changes.
=> Separates collision with obstacle and collision with vehicle

highway_env/envs/common/abstract.py, highway_env/envs/common/graphics.py, highway_env/envs/merge_env.py, highway_env/envs/parking_env.py, highway_env/envs/summon_env.py, highway_env/road/graphics.py, highway_env/road/objects.py, highway_env/road/road.py, highway_env/vehicle/graphics.py, highway_env/vehicle/kinematics.py, tests/vehicle/test_dynamics.py
This pull request proposes an initial implementation of the feature described in #56 
I should explain a few things:
1. Inheriting empty classes `Obstacle` and `Landmark` may be controversial, since adding just a property to `RoadObject` class might do the benefit I seek. But I did this for the sake of further development in the future.
2. Because `parking-env` used `to_dict()` method of the former `Obstacle` class, I had to implement that in the `RoadObjects`, but it doesn't make sense and I propose changing `parking-env` later on.
3. I've added a test for modified `check_collision()` function in the `test_dynamics.py` file, feel free to edit the location if you think it should be in another file.
Because of the many changes in master, I had to do a breathtaking rebase :sweat_smile: I …
=> Common interface for road objects

highway_env/envs/common/observation.py, highway_env/road/road.py
I propose some modifications related to the issue #66 :
I added both directions exo-vehicles observation in the KinematicObservation class, and set the ego-vehicle X position to zero in the observation when absolute == False
=> road.py: fix the error in close_vehicles_to();observation.py: adapt KinematicObservation and add see_behind

highway_env/envs/highway_env.py
fix bug when using highway-v0 with action type ContinuousAction
=> fix speed_to_index in highway env with continuous control

scripts/README.md, scripts/parking_her.ipynb
=> Upgrade HER example from SB2 to SB3

highway_env/envs/intersection_env.py, highway_env/vehicle/kinematics.py
See https://github.com/eleurent/highway-env/discussions/205
=> Handle continuous actions in intersection-v0

scripts/parking_her.ipynb
Hello,
As promised, here is the update for SB3>1.1.0 (with proper dictionary support).
Related: https://github.com/eleurent/highway-env/issues/188
=> Fixes for SB3>v1.1.0

README.md
Add an entry in the list of publications
=> Update README.md : Add an entry in the list of publications

README.md, docs/requirements.txt, docs/source/actions/index.rst, docs/source/faq.rst, docs/source/make_your_own.rst, docs/source/multi_agent.rst, docs/source/observations/index.rst, docs/source/quickstart.rst, highway_env/__init__.py, highway_env/envs/common/abstract.py, highway_env/envs/common/action.py, highway_env/envs/common/graphics.py, highway_env/envs/common/observation.py, highway_env/envs/exit_env.py, highway_env/envs/highway_env.py, highway_env/envs/intersection_env.py, highway_env/envs/parking_env.py, highway_env/envs/racetrack_env.py, highway_env/envs/roundabout_env.py, highway_env/envs/u_turn_env.py, scripts/README.md, scripts/utils.py, setup.cfg, tests/envs/test_actions.py, tests/envs/test_env_preprocessors.py, tests/envs/test_gym.py, tests/envs/test_time.py, tests/graphics/test_render.py
This PR should replace gym with [Gymnasium](https://gymnasium.farama.org/), as gym is no longer maintained and RL libraries have also migrated (RLlib) or are almost finishing migrating (SB3).
This PR also fixes #415 , regarding time limit truncation being on terminated flag.
=> Replace Gym with Gymnasium

README.md
add new work based on Highway-env
=> Update README.md:add new work based on Highway-env

highway_env/road/road.py
See https://github.com/Farama-Foundation/HighwayEnv/issues/495
=> Replace np.random.randint by np.random.integers

highway_env/road/road.py
See https://github.com/Farama-Foundation/HighwayEnv/issues/499
=> Move route id fix earlier

highway_env/road/road.py
Fix https://github.com/Farama-Foundation/HighwayEnv/issues/512
Thanks @SEUCGX for the reporting the issue and providing a fix.
=> Fix non-determinism in route planning

highway_env/envs/common/action.py, highway_env/envs/common/graphics.py, highway_env/vehicle/kinematics.py
This should enable predict_trajectory=True with continuous action spaces
Fix https://github.com/Farama-Foundation/HighwayEnv/issues/239
=> Add predict_trajectory to Vehicle

highway_env/envs/intersection_env.py, highway_env/vehicle/controller.py
See https://github.com/Farama-Foundation/HighwayEnv/issues/521
=> Replace randint by integers

highway_env/envs/common/observation.py
Fix https://github.com/Farama-Foundation/HighwayEnv/issues/541
=> Fix grid boundaries checks in OccupancyGridObservation

README.md
Hi, I added some publications from my lab that use highway-env
=> Added publications using highway-env

README.md
Good afternoon, I used highway-env as the base code for my recent work on adversarial policy learning and wanted to add it in here!
=> Adding project publication using highway-env

scripts/intersection_social_dqn.ipynb
see https://github.com/Farama-Foundation/HighwayEnv/issues/586
=> Fix testing of trained policy in notebook

highway_env/envs/parking_env.py
See https://github.com/Farama-Foundation/HighwayEnv/issues/593
=> Fix starting position of vehicles in parking env

highway_env/__init__.py, highway_env/envs/racetrack_env.py
Larger racetrack based on the pre-existing one.
This larger track also features 3 lanes.
LMK if you'd like to integrate @eleurent and how, cheers.
=> Add Large Racetrack
